### ISSUE TITLE
GetCourses of participant always has participant count of 1

### ISSUE THREAD

**Issue by geroembser** [corona-school/backend#115]
If using the GetCourses route with the optional `participant` ID parameter to request all courses that this participant has joined, the API will always return a participant count of 1, no matter of how many participants really joined that course. 

Also see https://github.com/corona-school/web-user-app/issues/56. Originally looked like a frontend issue, but actually seem to be API related.

**Comment by Ni42** [comment]
@BlobbyBob I guess this happens because of this join which limits the subcourse.participant LEFT JOIN to the current user:

https://github.com/corona-school/backend/blob/b50ce66fd7110d4ede2caea77227415c8e8d40ee/web/controllers/courseController/index.ts#L226
