### ISSUE TITLE
Add course join/leave events to Transaction Log

### ISSUE THREAD

**Issue by geroembser** [corona-school/backend#124]
We need to keep records on which tutee/pupil/participant has joined which course at which time. The same applies for leaving a course. At the moment, participants can leave the course, even if it has already began or the course was completed. To have more accurate information on how the course was used, we need to have those advanced statistics (beside the information who has actually participated in a lecture).

So we need to extend the transaction log to support the following:
- [ ] participant **joined** course: _participant id, joined (sub-)course id, time of join_
- [ ] participant **left** course: _participant id, left (sub-)course id, time of leave_

**Comment by Jonasdoubleyou** [comment]
https://github.com/corona-school/project-user/issues/472
