### ISSUE TITLE
Add Readme on how to create a database migration

### ISSUE THREAD

**Issue by geroembser** [corona-school/backend#129]
Our documentation lacks some explanations on how to create database migrations for our code. Since this is a quite common task, we should somewhere describe how to best generate (and even test locally) database migrations if someone modifies the entities. This should make it even simpler for new team members to generate and commit migrations as they're working on our code. 

Thanks to @kevinbischof for bringing this to my attention.

**Comment by kevinbischof** [comment]
I think it would be also useful to add a section to the main readme file, where it points to all the specific readme files like this one.
