### ISSUE TITLE
Health checks of fundamental endpoints

### ISSUE THREAD

**Issue by Jonasdoubleyou** [corona-school/backend#169]
Motivation: 
Currently the only way to detect issues is through users reporting problems.
That is bad user experience, also it takes time to find the root cause. 

Solution: Basic external health checks of fundamental Endpoints, to detect major issues affecting all users (service down, API failing)

Not in scope: Making sure that every flow works, that would also require functional checks of flows / user log collection.

Requirements:
- Alerts are reported via Slack
- Monitoring of all backends / frontends (5 checks), as well as some fundamental public APIs (~10)
- cheap

**Comment by Jonasdoubleyou** [comment]
Available SaaS solutions:

**pingdom**
https://www.pingdom.com/
- free trial limited to 30 days
- ~20€ / month (pricing scales with number of monitors)
- real browser testing / real user monitoring is also possible (maybe planned in future)

✅ Slack integration
⛔ not cheap

**UptimeRobot**
https://uptimerobot.com/
- TLS Certificate monitoring / Port monitoring (database / redis)  (paid version only)
- no real browser testing / real user monitoring possible

✅ Slack integration
✅ free plan covers 50 endpoints

**Visual Ping**
https://visualping.io/

⛔ expensive (58$ for ping every 5mins)
   -> does not fit the usecase

**Dynatrace**
https://dynatrace.com
Can monitor everything, can also collect logs, basically covers everything we'd ever need.
⛔ pricing "starts at" $11 / month and scales very well

**Site24x7**
https://www.site24x7.com/
⛔ pricing 35€ / month

**Uptrends**
https://www.uptrends.com/tools/uptime
⛔ free version only includes one site, otherwise costs 35$+/month

**StatusCake**
https://www.statuscake.com/
- also free Certificate Monitoring 
✅ free plan
⚠ 10 monitors (would be enough to cover the basics)

**Freshping**
https://www.freshworks.com/website-monitoring
- status page / badge / response time monitoring
- Also supports ICMP / port / DNS monitoring
- Pro version also covers custom HTTP headers and more fine tuning (which I don't think we need)

✅ free plan covers 50 endpoints (including all features listed above)
✅ Slack integration (use it)

**Comment by Jonasdoubleyou** [comment]
@geroembser @lsc0498 I checked a few alternatives to Freshping (the tool I use), and for our current usecase Freshping would be the best choice IMO (it's free, and will cover our usecase plus some interesting bonus features). I would proceed by creating an account there. Any objections?

**Comment by geroembser** [comment]
No, I have no objections. Sounds good. You're very welcome to set that up. Thanks a lot! 👍

**Comment by Jonasdoubleyou** [comment]
A Freshping account was created and integrated into Slack. All websites and the famous course API are now monitored
