### ISSUE TITLE
Add 'German as second language' information to registration process

### ISSUE THREAD

**Issue by lsc0498** [corona-school/backend#176]
This serves as prerequisite to solve corona-school/project-user#280 and corona-school/project-user#281.

- [x] To `pupil` add information about fluently spoken languages and 'learning German since'
- [x] To `student` add information 'supports in DaZ' and languages in which can be supported
- [x] Adapt `api/user` and `api/register` endpoints accordingly
- [x] Add migration

**Comment by realmayus** [comment]
Seems to be closed with #178
