### ISSUE TITLE
Invalid Jitsi-links when using special characters

### ISSUE THREAD

**Issue by reinerschristopher** [corona-school/backend#34]
While using the web-screening-admin I recognised that invalid Jitsi-links are created.

Student had a ' in her name (e.g. O'Niel). The created Jitsi-link shows a 404 error (see: https://meet.jit.si/o'niel).

Possible fix: strip all special characters or convert them to "-" (i.e. https://meet.jit.si/o-niel)

See web-screening-app issue # 3 

Does this happen while creating Jitsi-links for the matches in the backend?

**Comment by BlobbyBob** [comment]
The link is not generated in the backend.
